fetchai/cosmpy

HISTORY.md
setup.py

Added HISTORY.MD
Increased version of cosmpy

Added HISTORY.MD

---

cosmpy/clients/ledger.py
cosmpy/common/retrier.py
cosmpy/common/retry_manager.py
tests/test_clients/test_cosmos_ledger.py

Should be merged into #78 
Decreased code duplication for exception/retry handling

Retry manager implementation for high level API

---

Pipfile
cosmpy/aerial/client/__init__.py
cosmpy/aerial/contract/__init__.py
cosmpy/aerial/gas.py
scripts/run-checks.sh
scripts/run-fmt.sh
tests/unit/test_aerial/gas_test.py

This codes integrates an initial strategy engine for choosing the gas fees for a transaction. It uses a simple type based lookup table.
This PR covers the work for this offline case and lays the foundation for the simulation based strategy next. In this way this PR will solve half of #100

Aerial: Initial offline table based gas strategy

---

.github/workflows/workflow.yml
cosmpy/gov/__init__.py
cosmpy/gov/interface.py
cosmpy/gov/rest_client.py
scripts/check_copyright.py
tests/test_gov/__init__.py
tests/test_gov/test_rest_client.py
tox.ini

gov module queries support

---

cosmpy/aerial/client/__init__.py
cosmpy/aerial/client/utils.py
cosmpy/aerial/contract/__init__.py
cosmpy/aerial/gas.py
cosmpy/aerial/tx_helpers.py
cosmpy/vulture_whitelist.py
scripts/run-checks.sh
tests/unit/test_aerial/gas_test.py

Added new simulation based gas estimation API. This is now the default mechanism for sending transactions.
Additionally did some refactoring to remove duplicate logic around sending of the transactions
Fixes #100 
Fixes #101 
Laid ground work for #98

Aerial: Simulation based Gas estimation

---

cosmpy/clients/ledger.py
examples/capricorn_send_rest_example.py
tests/test_clients/test_cosmos_ledger.py

Added support for TX fees and pulling max_gas_limit from node
Should be merged into refactor/high_level_clients_capricorn #78

Tx fees fixes

---

.github/workflows/workflow.yml
.gitignore
Makefile
cosmpy/bank/rest_client.py
setup.cfg
tox.ini

unused darglint config removed from the setup.cfg

unused darglint config removed from the setup.cfg

---

cosmpy/aerial/client/__init__.py
cosmpy/params/__init__.py
cosmpy/params/interface.py
cosmpy/params/rest_client.py
cosmpy/tx/rest_client.py
tests/unit/test_params/__init__.py
tests/unit/test_params/test_params_client.py

Also fix the simulate call that now make a proper post and pass the transaction

feat: add params rest client

---

docs/governance.md
docs/index.md
mkdocs.yml

This PR makes minor docs edits:
* hints coming soon for Governance
* Takes out commented code
* Reflects the above in `mkdocs`
* Removes the empty atomic-swap page

Minor docs edit

---

HISTORY.md
setup.py

This PR prepares for the 0.3.0 release.

Feature/release 0.3.0

---

Makefile
cosmpy/aerial/client/__init__.py
tests/integration/__init__.py
tests/integration/test_bank/test_bank.py
tests/integration/utils/Dockerfile
tests/integration/utils/__init__.py
tests/integration/utils/chain.py
tests/integration/utils/container.py
tests/integration/utils/entrypoint.sh
tests/integration/utils/testcase.py

- fix: make vulture only report 100% confidence dead code
- tests: add integration test harness

tests: dorado integration tests

---

HISTORY.md
setup.py

Release 0.4.0

---

MANIFEST.in
cosmpy/aerial/contract/cosmwasm.py
tests/unit/test_aerial/contract/__init__.py
tests/unit/test_aerial/contract/test_cosmwasm_handlers.py

This change corrects support for sending funds with execute and instantiate messages

fix: send funds in contract methods

---

docs/low-level-api.md
docs/wallets-and-keys.md

As a first-time user of cosmpy, coming to it fresh, with only a mnemonic and a use case, I found it quite difficult to progress beyond the high level API examples given.  I offer the attached code in the hope that it will allow others to get stuck into using cosmpy, and postpone the necessity of diving into bip-39, bip-44, bpi_utils and protobuf documentation!

docs: Add additional documentation

---

docs/low-level-api.md
docs/wallets-and-keys.md
mkdocs.yml

This PR makes edits to the wallet and low-level-api documentation pages.

Fix low level docs

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

This PR makes small modifications to GH issues templates.

chore: modifications to the GH templates

---

cosmpy/aerial/wallet.py

This PR adds the ability to add address prefix in the wallet. It is a copy of #158 which passes CI.

Add address prefix to wallet

---

docs/auto-compounder.md
examples/aerial_compounder.py
mkdocs.yml

* Slight modification to aerial_compounder.py to get a consistent time in each loop
* Added staking auto compounded doc

docs: add auto-compounder guide

---

docs/swap-automation.md
examples/aerial_swap_automation.py

Added use-case that begins with a certain amount of atestfet, then it swaps the whole amount for cw20 tokens using a liquidity pool if a threshold price is reached. The same happens when holding cw20 tokens using a different threshold

Swap automation

---

examples/aerial_atomic_swap.py
examples/aerial_authz.py
examples/aerial_compounder.py
examples/aerial_deploy_contract.py
examples/aerial_oracle.py
examples/aerial_oracle_client.py
examples/aerial_send_tokens.py
examples/aerial_stake_optimizer.py
examples/aerial_staking.py
examples/aerial_topup.py

Updating CosmPy examples with FaucetApi, argparse and some other minor changes

feat: authz and swap update

---

DEVELOPING.md

according to: https://github.com/fetchai/cosmpy/issues/64

fix fetchd instruction in DEVELOPING.md

---

.github/workflows/workflow.yml

check integration tests works well on windows platform

integration tests on windows

---

cosmpy/common/rest_client.py
tests/unit/test_common/test_rest_client.py

This PR adds tests for common rest_client module as a response to https://github.com/fetchai/cosmpy/issues/70

Add test for common rest_client

---

.github/workflows/workflow.yml
tox.ini

CI workflow improvements:
* dedicated checks for code quality
* unit tests
* integration tests
* version checkouts for CI actions

Improve CI workflow

---

mkdocs.yml

Added swap-automation.md to mkdocs.yml

feat: added swap auto to mkdocs

---

Makefile

https://github.com/fetchai/cosmpy/issues/277

cleanup: Makefile review and improvement

---

cosmpy/aerial/client/__init__.py

This fixes https://github.com/fetchai/cosmpy/issues/293.

fix: import PubKey type to prevent error on rest query

---

.github/workflows/workflow.yml
cosmpy/aerial/contract/__init__.py
docs/api/aerial/contract/__init__.md
poetry.lock
tests/integration/test_contract.py
tox.ini

feat: support instantiating contract with code id only

---

cosmpy/aerial/client/__init__.py
cosmpy/aerial/client/utils.py
cosmpy/aerial/faucet.py
docs/api/aerial/client/utils.md
tests/integration/examples/__init__.py
tests/integration/examples/test_staking_example.py
tests/integration/test_contract.py

according to https://github.com/fetchai/cosmpy/issues/273

staking summary pagination support

---

.github/workflows/release.yml

* release v0.6.1
* fix for releae CI

fix (#307)

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/PULL_REQUEST_TEMPLATE/release.md
.github/pull_request_template.md
.github/workflows/docs_pr_preview.yml
.github/workflows/release.yml
CONTRIBUTING.md
DEVELOPING.md
README.md
docs/auto-compounder.md
docs/index.md
docs/liquidity-pool.md
docs/low-level-api.md
docs/oracles.md
docs/stake-optimizer.md
docs/swap-automation.md
docs/wallet-topup.md

This PR updates the repo for the change from `master` to `main`.

refactor: change `master` to `main`

---

pyproject.toml

Release v0.8.0
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply._

release: bump version to v0.8.0

---

poetry.lock
pyproject.toml

Move googleapis-common-protos to main dependency group. Fixes basic installation failure.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply._

fix: move googleapis-common-protos to main deps

---

.wordlist.txt
HISTORY.md
pyproject.toml

Release v0.9.1
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply._

chore: bump version to 0.9.1 and add release notes

---

.github/CODEOWNERS

Updated set of CODEOWNERS

---

.wordlist.txt
HISTORY.md
pyproject.toml

Release v0.9.2
Links to any issues resolved.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply._

chore: add history entry and bump version to 0.9.2 for release

---

DEVELOPING.md
README.md
docs/low-level-api.md
docs/wallets-and-keys.md
mkdocs.yml
pyproject.toml

Fixed outdated links to fetch.ai docs
_What type of change does this pull request make (put an `x` in the boxes that apply)?_
_Put an `x` in the boxes that apply:_
_[if this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...]_

fix: links

---

cosmpy/aerial/client/utils.py
cosmpy/aerial/coins.py
cosmpy/aerial/tx.py

_[describe the changes here...]_
_[if applicable, add links to issues resolved by this PR]_
_What type of change does this pull request make (put an `x` in the boxes that apply)?_
_Put an `x` in the boxes that apply:_
_[if this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...]_

Refactor TxFee (getter/setter properties), adding 'to_coins(...)' function
